BEGIN TRANSACTION;

INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:54.334');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:55.328');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:55.678');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.239');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.632');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.633');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.634');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.635');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.636');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.637');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.638');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.639');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.640');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.641');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.642');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.643');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.644');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.645');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.646');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.647');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.648');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.649');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.650');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.651');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.652');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.653');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.654');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.655');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.656');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.657');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.658');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.659');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.660');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.661');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.662');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.663');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.664');
INSERT into courses (name, image, type, author, info, created) values ('Coursename in the shadows', '', 'course', 'Author In The Shadows', 'Very cool course, yeah. I swear, really!', '2020-10-30 22:25:56.664');

COMMIT;
