const CardsActionTypes = {
  FETCH_CONTENT_START: "FETCH_CONTENT_START",
  FETCH_CONTENT_SUCCESS: "FETCH_CONTENT_SUCCESS",
  FETCH_CONTENT_FAILURE: "FETCH_CONTENT_FAILURE",
  FETCH_FIRST_BOOKS_START: "FETCH_FIRST_BOOKS_START",
  FETCH_FIRST_BOOKS_SUCCESS: "FETCH_FIRST_BOOKS_SUCCESS",
  FETCH_FIRST_BOOKS_FAILURE: "FETCH_FIRST_BOOKS_FAILURE",
  FETCH_PORTION_OF_BOOKS_START: "FETCH_PORTION_OF_BOOKS_START",
  FETCH_PORTION_OF_BOOKS_SUCCESS: "FETCH_PORTION_OF_BOOKS_SUCCESS",
  FETCH_PORTION_OF_BOOKS_FAILURE: "FETCH_PORTION_OF_BOOKS_FAILURE",
  FETCH_FIRST_COURSES_START: "FETCH_FIRST_COURSES_START",
  FETCH_FIRST_COURSES_SUCCESS: "FETCH_FIRST_COURSES_SUCCESS",
  FETCH_FIRST_COURSES_FAILURE: "FETCH_FIRST_COURSES_FAILURE",
  FETCH_PORTION_OF_COURSES_START: "FETCH_PORTION_OF_COURSES_START",
  FETCH_PORTION_OF_COURSES_SUCCESS: "FETCH_PORTION_OF_COURSES_SUCCESS",
  FETCH_PORTION_OF_COURSES_FAILURE: "FETCH_PORTION_OF_COURSES_FAILURE",
  UPDATE_CARD: "UPDATE_CARD",
  DELETE_CARD: "DELETE_CARD",
  ADD_CARD: "ADD_CARD",
};

export default CardsActionTypes;
